### ISSUE TITLE
Repeating keys

### ISSUE THREAD

**Issue by Dudz51** [adrianglz64/snappyrom#6]
For TMP, can you put a $00 in location $80f7 before putting it on the cart? or is there way to customize this myself?

**Comment by adrianglz64** [comment]
So basically you want to disable key repeat in TMP?  I have to admit I've been annoyed by it a few times myself, but probably more because TMP seems to speed up the keyboard scan rate than because of the key repeat itself.

You can fire up your favorite ex editor and look for the pattern 78 20 a0 a4 a9 80.  You should find it twice, as the ROM contains the both the c64-only and the c64+REU versions of TMP.  Just replace that last 80 with a 00 in both instances and you should be set.

I went ahead and patched the .crt files for you, and they seem to work fine in vice for both NTSC and PAL, with and without REU.

[snappyrom-5.32-beta-no-tmp-key-repeat.zip](https://github.com/adrianglz64/snappyrom/files/12394506/snappyrom-5.32-beta-no-tmp-key-repeat.zip)

I'm not sure how I'd go about including this as an option in the ROM.  I have to assume most users expect keys to repeat in TMP.  In the meantime I hope these crt files do the trick for you.

**Comment by Dudz51** [comment]
Thank you so much!
