### ISSUE TITLE
Multi Drive Wedge Issue

### ISSUE THREAD

**Issue by NymeeXX** [adrianglz64/snappyrom#7]
First let me thank you for this project combining two of my favorite cartridges.  
Note I'm using JiffyDOS as well and prefer not to disable it.  
When I change drives with @#9 for example, then use load and run (up arrow) it always  loads from drive 8, not the newly selected drive.  Same behavior with the % load and ' verify.  Standard wedge keys like / and left arrow (save) work fine.  
Seems like the combined wedges don't always honor the drive when changed from 8.
Thanks.

**Comment by adrianglz64** [comment]
No problem, I'm glad you find it useful!

Ok, so I have to admit I never thought of trying to use the JD wedge when the Super Snapshot cart is enabled.  I've made a few tweaks to the SS wedge and have looked at the code for the JD wedge as well recently.  When SS is enabled, the SS wedge will take precedence, so it will handle the following commands:

```
%   load ml
/   load basic
>   drive status/commands
@   drive status/commands (alias for >)
$   list dir
<-  save (arrow left)
!   display seq file
B   check for BOOT/OLD/FCOPY/DCOPY
O   check for BOOT/OLD/FCOPY/DCOPY
F   check for BOOT/OLD/FCOPY/DCOPY
D   check for BOOT/OLD/FCOPY/DCOPY
```

Anything not on that list will be handled by the JD wedge, so that would explain why verify (') and load and run (arrow up) don't work as expected.  I don't see how % could fail, though.  Would you mind verifying that?

As I mentioned, I've been looking at the code for the JD wedge recently anyway, so I'll go ahead and check where it gets the device number from and see if I can have the SS wedge set it there too.

**Comment by NymeeXX** [comment]
Hey, had a second look and indeed % works on the selected drive as expected.  Sorry for the confusion.
Certainly appreciate any efforts on improving the JD wedge.  The mere fact you have the wedges working together is awesome.  I follow Robin Harbron and was really excited when he mentioned your Snappyrom had the SS and JD wedges (and fast loaders) playing together nicely cause as you know , there were some bad conflicts before. 
Take care.

**Comment by adrianglz64** [comment]
Ok, I had to take a deep dive into both the SS and the JD wedges for this one, but I think I've got it.

I figured I'd make it work both ways while I was at it.  Basically, when you do something like ``@#9``, it gets handled by the SS wedge, but now it also updates JD's idea of what the current device is, so JD wedge stuff like load and run will use the new device too.

In the other direction, you can press CTRL-D, which is handled by the JD kernal, and it finds the next available device and prints it out.  The SS wedge will now pick that up too and use it.

Please let me know if you find any cases where you think it's not behaving like it should.  If all goes well, I'll be including this feature in the next release in about a couple of weeks.

Note:  The version number is ugly for now.  I'll probably make it 5.33 for the release.

[snappyrom-5.32-beta02.zip](https://github.com/adrianglz64/snappyrom/files/12444093/snappyrom-5.32-beta02.zip)

**Comment by NymeeXX** [comment]
I've been playing around for a bit and you seem to have addressed the @# dive issues I raised.
Snappyrom will be my cartridge of choice moving forward.
Again, thanks.

**Comment by adrianglz64** [comment]
Glad it worked for you!  Thanks for testing it.  Closing this as resolved.
