### ISSUE TITLE
Random unexpected error

### ISSUE THREAD

**Issue by Dudz51** [adrianglz64/snappyrom#8]
I got "@" happy evidently with the SnappyRom crt in.. I saved a file, I meant to overwrite using @:
I did a directory listing and put @ for some reason in, I got a WiFi error? Is this the .crt or vice??

![Screenshot 2023-09-14 162129](https://github.com/adrianglz64/snappyrom/assets/142706099/01a98067-0922-4a66-a36c-9c0628ab9bce)

**Comment by adrianglz64** [comment]
Looks like you accidentally stumbled upon the one feature in the ROM that actually requires my cartridge.
I modified the ``@@`` wedge command to add a quick shortcut to the codenet server included in the ROM (see <http://www.oxyron.de/html/codenet.html> for a description of codenet).  It only works with the wifi module in my cartridge for now.

In the orignal SSv5 ROM, the ``@@MON`` wedge command enters the ML monitor (mapped to the F8 key).  It actually only checks for @@ and ignores the rest.  I added a check for @@C, which starts codenet.

So why did it try to start codenet if you didn't type ``@@C``?  It's trying to be smart!  It checks for quotes where they would normally occur in a directory listing, and if found, it skips everything after the @ symbol and continues after the double quote.

In your example it turned ``@    "@CONV.ML"`` into ``@@CONV.ML``, so it tried to start codenet.  I actually had to work around this for the ``@CD`` command so that you could use it in a directory listing without having to clean up the line manually.  I'll see if I can reuse that code to prevent all @ commands from advancing like that.
